# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Contentfulcommander < Formula
  desc "A toolbox of non-trivial Contentful interactions"
  homepage "https://github.com/foomo/contentfulcommander"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/contentfulcommander/releases/download/v0.1.0/contentfulcommander_0.1.0_darwin_amd64.tar.gz"
      sha256 "031634ec8b689c2b858b17042cb614dd967c76c6950e94be8de706bab686797a"

      def install
        bin.install "contentfulcommander"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/contentfulcommander/releases/download/v0.1.0/contentfulcommander_0.1.0_darwin_arm64.tar.gz"
      sha256 "1ed8ff1156bf905ec43f98d9e3ae89b4f5c14dee2b3cb8e333c5cee9d00a3811"

      def install
        bin.install "contentfulcommander"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/contentfulcommander/releases/download/v0.1.0/contentfulcommander_0.1.0_linux_amd64.tar.gz"
      sha256 "c0d10d9af040bf1527fa6df026e0b984ef0128ac57aae320bf3269b662540c38"

      def install
        bin.install "contentfulcommander"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/contentfulcommander/releases/download/v0.1.0/contentfulcommander_0.1.0_linux_arm64.tar.gz"
      sha256 "0c2056932c6f4b6ad4df0d89bc008042e2f7e1d1a38e516a93b434f496ab248a"

      def install
        bin.install "contentfulcommander"
      end
    end
  end

  def caveats
    <<~EOS
      contentfulcommander help
    EOS
  end
end
