# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Posh < Formula
  desc "Project Oriented SHELL"
  homepage "https://github.com/foomo/posh"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/foomo/posh/releases/download/v0.1.0/posh_0.1.0_darwin_arm64.tar.gz"
      sha256 "e1bf02fdff454f0184603d44bc45668fba0b1353e3622e8c45ab4eff913bd248"

      def install
        bin.install "posh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/foomo/posh/releases/download/v0.1.0/posh_0.1.0_darwin_amd64.tar.gz"
      sha256 "05894d7b87acdb18fabde2c2f227e5519ee87915c81a20937f686c48c6a5fe0b"

      def install
        bin.install "posh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/posh/releases/download/v0.1.0/posh_0.1.0_linux_arm64.tar.gz"
      sha256 "e876c4e0ee4946627c50422d14b2322089f3fbc8ca9df985ef50930f4fcc4c67"

      def install
        bin.install "posh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/foomo/posh/releases/download/v0.1.0/posh_0.1.0_linux_amd64.tar.gz"
      sha256 "e04cf18e6280b31bf68088e67ff54178e3aa6e854de8ad130f152572b6fdb89c"

      def install
        bin.install "posh"
      end
    end
  end

  def caveats
    <<~EOS
      posh help
    EOS
  end
end
